#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '-----------------------------------------------------------------------'
echo '-- 🏗️👷 Checking formats, testing and building your project before committing  --'
echo '-----------------------------------------------------------------------'

# Check ESLint Standards
npm run check-lint ||
    (
        echo '----------------------------------------------------------------------'
        echo '🤯🥶 Formatting and Linting checks failed. Make the required changes listed above, add changes and try to commit again.'
        echo 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
        false
    )

# If everything passes... Now we can commit
echo ' ------------------------------------------------------------'
echo '|        ✅✅✅✅ Yeppie, all test passed!!                     |'
echo '|        😁🤗 Begin comitting...... 👍👍                      |'
echo ' ------------------------------------------------------------'
