name: Linter

on:
    pull_request:
        branches:
            - "**"

jobs:
    run:
        name: Linter
        runs-on: ubuntu-latest

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v4

            - name: Set Node.js version
              uses: actions/setup-node@v1
              with:
                  node-version: 22

            - name: Install dependencies
              run: npm ci

            - name: Run Formatter
              run:  
                npm run format-check 

            - name: Run Linter
              run:  
                npm run lint
